openapi: 3.0.3
info:
  description: REST API definitions for Taskmaster
  title: Taskmaster
  version: "0"
servers:
- description: API server
  url: /api
paths:
  /v1/runs:
    get:
      operationId: getRuns
      parameters:
      - in: query
        name: limit
        schema:
          default: 10000
          minimum: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRunsResponse'
          description: OK
      summary: Get runs
  /v1/tasks:
    get:
      operationId: getTasks
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTasksResponse'
          description: OK
      summary: Get tasks
components:
  schemas:
    TaskrunnerTask:
      properties:
        description:
          type: string
        name:
          type: string
        script:
          type: string
      type: object
    TaskrunnerTaskRun:
      properties:
        endTimestamp:
          format: int64
          nullable: true
          type: integer
        exitCode:
          nullable: true
          type: integer
        pid:
          nullable: true
          type: integer
        runNumber:
          minimum: 0
          type: integer
        startTimestamp:
          format: int64
          type: integer
        taskName:
          type: string
      type: object
    ListRunsResponse:
      properties:
        runs:
          items:
            $ref: '#/components/schemas/TaskrunnerTaskRun'
          type: array
      required:
      - runs
      type: object
    ListTasksResponse:
      properties:
        tasks:
          items:
            $ref: '#/components/schemas/TaskrunnerTask'
          type: array
      required:
      - tasks
      type: object
